let filter="all",timer,seconds,current;
document.getElementById("year").textContent=new Date().getFullYear();
function render(){let a=filter==="all"?MATCHES:MATCHES.filter(x=>x.type===filter);document.getElementById("status").textContent=`${a.length} partido(s) mostrado(s) en esta versión.`;document.getElementById("matches").innerHTML=a.map(m=>`<article class="match"><div class="comp">${m.flag} ${m.competition}</div><div class="date">${m.date}</div><div class="teams"><div class="team">${m.home}</div><div class="vs">VS</div><div class="team">${m.away}</div></div><button class="analyze" onclick="start('${m.id}')">🔍 Analizar partido</button></article>`).join("")}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()});
function loadMatches(){document.getElementById("status").textContent="Actualización preparada. La conexión automática se activará con la API deportiva.";render()}
function start(id){current=MATCHES.find(x=>x.id===id);seconds=300;document.getElementById("modalTitle").textContent=current.home+" vs "+current.away;document.getElementById("modal").classList.remove("hidden");document.getElementById("final").classList.add("hidden");document.getElementById("countdown").textContent="05:00";clearInterval(timer);timer=setInterval(()=>{seconds--;document.getElementById("countdown").textContent=String(Math.floor(seconds/60)).padStart(2,"0")+":"+String(seconds%60).padStart(2,"0");if(seconds<=0){clearInterval(timer);finish()}},1000)}
function finish(){let n=(current.home.length*7+current.away.length*11)%3;document.getElementById("prediction").textContent=n===0?current.home+" 2 — 1 "+current.away:n===1?current.home+" 1 — 1 "+current.away:"Gana "+current.home;document.getElementById("final").classList.remove("hidden");sound()}
function sound(){let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let c=new A(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.setValueAtTime(.001,c.currentTime);g.gain.exponentialRampToValueAtTime(.12,c.currentTime+.03);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.4);o.start();o.stop(c.currentTime+.4)}
function closeModal(){clearInterval(timer);document.getElementById("modal").classList.add("hidden")}
render();